### ISSUE TITLE
SyntaxError: Unterminated template literal

### ISSUE THREAD

**Issue by deadlysyntax** [ben-eb/postcss-ordered-values#29]
Got this error using version 2.2.3:

ERROR in .//css-loader!.//bootstrap/dist/css/bootstrap.css
Module build failed: /Users/jaap/Sites/auxiliary/node_modules/postcss-ordered-values/dist/rules/border.js:14
'hidden', 'dotted',`'dashed', 'solid', 'double', 'groove', 'ridge', 'inset', 'outset'];
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: Unterminated template literal
at Object.exports.runInThisContext (vm.js:73:16)

Note the backtick between the words 'dotted' and 'dashed'.

**Comment by ben-eb** [comment]
I checked the build from npm and it doesn't have this. Is it something else in your environment? Did you try reinstalling the module?

**Comment by deadlysyntax** [comment]
I believe it to be a dependency of one of my other packages because I didn't install it myself. What's the best way to find the dependent package?

**Comment by ben-eb** [comment]
I would recommend reinstalling your `node_modules` and trying again, I don't know why a rogue backtick is there but it's definitely not showing with a fresh install. 😄

**Comment by ben-eb** [comment]
Closing as stale, hope this is resolved. 👍
